sudo: required
services: 
  - docker

  before_install:
    - docker build -t farzana/docker-react -f Dockerfile.dev .
script:
  - docker run farzana/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-2468092"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"